### DISCUSSION TITLE
Why was this setup not working for me until I changed WORKDIR /usr/src/app to simply WORKDIR /app?

### DISCUSSION THREAD

**Discussion by igalci** [godd0t/django-docker-quickstart#2] [General]
I am learning Docker and trying to understand this.

My Django app was empty and returned "no module found" until I changed the WORKDIR from /usr/src/app to /app. 

Why is that?

**Comment by godd0t** [comment]
Hi @igalci,

I'm glad to hear you're learning Docker, and I'm sorry to hear you ran into some trouble. I want to make sure I understand your situation correctly to provide the best help possible. Can you provide a bit more information?

1. Did you make any other changes to the Dockerfile or docker-compose.yml apart from changing the WORKDIR?
2. Are you running any other Docker containers that might interfere with the paths?
3. Can you share the exact error message you saw when you encountered the "no module found" error?

 These additional details will help me better understand the context and guide you through to a solution.

**Comment by igalci** [comment]
Hey @godd0t , Yes I modified the configuration a bit.

Firstly, my app is in the root directory and not in the src folder. So I updated that in the dockerfile anywhere the source included the src/ (not the destination).

I also removed Redis and Celery. I used Django-Q so I changed it to that.

Here is my updated dockerfile: 

```
`FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN --mount=type=cache,target=/var/cache/apt \
	apt-get update && \
    apt-get install --no-install-recommends -y build-essential libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install pip --upgrade \
    && pip install -r requirements.txt

COPY . .

#COPY deployment/scripts ./deployment/scripts

RUN chmod -R +x deployment/scripts/*
`
```

**Reply by godd0t** [reply]
What about `docker-compose.yml`. As per current configuration:

```
backend:
    container_name: "${APP_NAME}-backend"
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        - APP_NAME=${APP_NAME}
        - APP_HOST=${APP_HOST}
        - APP_PORT=${APP_PORT}
    volumes:
      - ./src:/usr/src/app/
      - ./deployment/scripts:/app/deployment/scripts/
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: [ "/bin/sh", "/app/deployment/scripts/backend/start.sh" ]
```

did you change the volume part
```
  volumes:
    - ./src:/usr/src/app/
```

**Reply by igalci** [reply]
No, that part remains the same. 

Here is my segmet of the docker-compose: 

```
  backend:
    container_name: "${APP_NAME}-backend"
    build:
      context: .
      dockerfile: deployment/Dockerfile
      args:
        - APP_NAME=${APP_NAME}
        - APP_HOST=${APP_HOST}
        - APP_PORT=${APP_PORT}
    volumes:
       - ./src:/usr/src/app/
       - ./deployment/scripts:/app/deployment/scripts/
      - static_files:/usr/src/app/static
      - media_files:/usr/src/app/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-backend.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-backend.entrypoints=web"
      - "traefik.http.services.${APP_NAME}-backend.loadbalancer.server.port=${APP_PORT:-8000}"
    env_file: .env
    expose:
      - "${APP_PORT:-8000}"
    command: [ "/bin/sh", "/app/deployment/scripts/start.sh" ]
```
